import { useMemo, useState } from 'react';
import { Button } from '../common/Button';
import { FilterBar, StatusDot } from './AdminPrimitives';
import type { AdminAmbulance, AdminEmergency, AdminHospital, AdminReport, AdminUser } from '../../types/admin';

const tone = (status: string): 'good' | 'warning' | 'danger' | 'neutral' => status.toLowerCase().includes('active') || status.toLowerCase().includes('verified') || status.toLowerCase().includes('available') || status.toLowerCase().includes('operational') || status.toLowerCase().includes('resolved') ? 'good' : status.toLowerCase().includes('pending') || status.toLowerCase().includes('limited') || status.toLowerCase().includes('investigating') || status.toLowerCase().includes('en route') ? 'warning' : status.toLowerCase().includes('suspended') || status.toLowerCase().includes('offline') || status.toLowerCase().includes('unavailable') || status.toLowerCase().includes('high') ? 'danger' : 'neutral';

export const EmergencyTable = ({ data }: { data: AdminEmergency[] }) => <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">Request</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Hospital</th><th className="px-5 py-3">Ambulance</th><th className="px-5 py-3">ETA</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{data.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-3.5 font-semibold text-slate-900">{item.id}<p className="text-[11px] font-normal text-slate-400">{item.area}</p></td><td className="px-5 py-3.5 text-slate-600">{item.category}</td><td className="px-5 py-3.5 text-slate-600">{item.hospital}</td><td className="px-5 py-3.5 font-medium">{item.ambulance}</td><td className="px-5 py-3.5 font-semibold">{item.eta}</td><td className="px-5 py-3.5"><StatusDot label={item.status} tone={tone(item.status)} /></td></tr>)}</tbody></table></div>;

export const HospitalTable = ({ data }: { data: AdminHospital[] }) => { const [query, setQuery] = useState(''); const [items, setItems] = useState(data); const filtered = useMemo(() => items.filter((x) => `${x.name} ${x.area}`.toLowerCase().includes(query.toLowerCase())), [items, query]); return <div><div className="p-4"><FilterBar placeholder="Search hospitals or areas" onSearch={setQuery} /></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">Hospital</th><th className="px-5 py-3">Verification</th><th className="px-5 py-3">Emergency status</th><th className="px-5 py-3">Availability</th><th className="px-5 py-3">Last updated</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id}><td className="px-5 py-3.5 font-semibold">{item.name}<p className="text-[11px] font-normal text-slate-400">{item.area}</p></td><td className="px-5 py-3.5"><StatusDot label={item.verification} tone={tone(item.verification)} /></td><td className="px-5 py-3.5"><StatusDot label={item.emergencyStatus} tone={tone(item.emergencyStatus)} /></td><td className="px-5 py-3.5 text-slate-600">{item.availability}</td><td className="px-5 py-3.5 text-slate-500">{item.lastUpdated}</td><td className="px-5 py-3.5"><StatusDot label={item.accountStatus} tone={tone(item.accountStatus)} /></td><td className="px-5 py-3.5"><div className="flex gap-1"><Button type="button" size="sm" variant="ghost">View</Button><Button type="button" size="sm" variant="secondary" onClick={() => setItems((current) => current.map((x) => x.id === item.id ? { ...x, verification: x.verification === 'Verified' ? 'Pending' : 'Verified' } : x))}>{item.verification === 'Verified' ? 'Unverify' : 'Verify'}</Button><Button type="button" size="sm" variant="ghost" onClick={() => setItems((current) => current.map((x) => x.id === item.id ? { ...x, accountStatus: 'Suspended' } : x))}>Suspend</Button></div></td></tr>)}</tbody></table></div></div>; };

export const AmbulanceTable = ({ data }: { data: AdminAmbulance[] }) => { const [items, setItems] = useState(data); return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">Ambulance</th><th className="px-5 py-3">Operator</th><th className="px-5 py-3">Online</th><th className="px-5 py-3">Current status</th><th className="px-5 py-3">Assignment</th><th className="px-5 py-3">ETA</th><th className="px-5 py-3">Last update</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="px-5 py-3.5 font-semibold">{item.id}</td><td className="px-5 py-3.5 text-slate-600">{item.operator}</td><td className="px-5 py-3.5"><StatusDot label={item.online ? 'Online' : 'Offline'} tone={item.online ? 'good' : 'neutral'} /></td><td className="px-5 py-3.5"><StatusDot label={item.status} tone={tone(item.status)} /></td><td className="px-5 py-3.5 text-slate-600">{item.assignment}</td><td className="px-5 py-3.5 font-semibold">{item.eta}</td><td className="px-5 py-3.5 text-slate-500">{item.lastUpdate}</td><td className="px-5 py-3.5"><div className="flex gap-1"><Button type="button" size="sm" variant="ghost">View</Button><Button type="button" size="sm" variant="secondary" onClick={() => setItems((current) => current.map((x) => x.id === item.id ? { ...x, online: !x.online, status: !x.online ? 'Available' : 'Offline' } : x))}>{item.online ? 'Suspend' : 'Activate'}</Button></div></td></tr>)}</tbody></table></div>; };

export const UserTable = ({ data }: { data: AdminUser[] }) => <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">User ID</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Emergency requests</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{data.map((item) => <tr key={item.id}><td className="px-5 py-3.5 font-semibold">{item.id}</td><td className="px-5 py-3.5"><StatusDot label={item.accountStatus} tone={tone(item.accountStatus)} /></td><td className="px-5 py-3.5 font-semibold">{item.emergencyRequests}</td><td className="px-5 py-3.5 text-slate-500">{item.createdDate}</td><td className="px-5 py-3.5 text-slate-600">{item.status}</td></tr>)}</tbody></table></div>;

export const ReportTable = ({ data }: { data: AdminReport[] }) => { const [items, setItems] = useState(data); return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-5 py-3">Report</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="px-5 py-3.5 font-semibold">{item.id}</td><td className="px-5 py-3.5 text-slate-600">{item.category}</td><td className="px-5 py-3.5"><StatusDot label={item.priority} tone={tone(item.priority)} /></td><td className="px-5 py-3.5"><StatusDot label={item.status} tone={tone(item.status)} /></td><td className="px-5 py-3.5 text-slate-500">{item.createdTime}</td><td className="px-5 py-3.5"><Button type="button" size="sm" variant="secondary" onClick={() => setItems((current) => current.map((x) => x.id === item.id ? { ...x, status: x.status === 'Resolved' ? 'Open' : 'Resolved' } : x))}>{item.status === 'Resolved' ? 'Reopen' : 'Resolve'}</Button></td></tr>)}</tbody></table></div>; };
