import { ArrowRight, Phone } from 'lucide-react';
import { Button } from '../common/Button';
import { MapView } from '../map/MapView';
import type { NavigationState } from '../../types/ambulance';
import type { RouteOptionItem } from '../../types/route';
import type { UserLocation } from '../../types/facility';

interface NavigationPanelProps { title: string; destinationName: string; destinationAddress: string; destinationCoordinates: { latitude: number; longitude: number }; navigation: NavigationState; userLocation: UserLocation; route: RouteOptionItem; onAction: () => void; actionLabel: string; onCall?: () => void; }

export const NavigationPanel = ({ title, destinationName, destinationAddress, destinationCoordinates, navigation, userLocation, route, onAction, actionLabel, onCall }: NavigationPanelProps) => (
  <div className="flex flex-1 flex-col"><div className="grid flex-1 grid-rows-[minmax(300px,52vh)_auto] lg:grid-cols-[1.4fr_0.6fr] lg:grid-rows-none">
    <div className="relative min-h-[300px] overflow-hidden bg-slate-200 lg:min-h-[calc(100vh-61px)]"><MapView userLocation={userLocation} center={userLocation} destination={{ ...destinationCoordinates, name: destinationName, address: destinationAddress, isEmergency: title === 'Navigate to Patient' }} activeRoute={route} alternativeRoutes={[]} currentStepIndex={navigation.currentStepIndex} isNavigating interactive className="h-full w-full" /><div className="absolute left-3 right-3 top-3 z-30 sm:left-4 sm:right-auto sm:w-[420px]"><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 shadow-lg"><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">{title}</p><p className="mt-1 text-lg font-semibold text-slate-950">{navigation.instruction}</p></div></div></div>
    <section className="flex flex-col bg-white"><div className="flex-1 space-y-5 p-4 sm:p-6"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Destination</p><h1 className="mt-1 text-xl font-bold tracking-tight text-slate-950">{destinationName}</h1><p className="mt-1 text-sm text-slate-500">{destinationAddress}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">ETA</p><p className="mt-1 text-2xl font-bold">{navigation.eta}</p></div><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">Distance</p><p className="mt-1 text-2xl font-bold">{navigation.distance}</p></div></div><div className="flex items-start gap-3 rounded-lg border border-slate-200 p-4"><div className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-md bg-slate-100"><ArrowRight className="h-5 w-5 text-slate-700" /></div><div><p className="text-xs text-slate-500">Next navigation instruction</p><p className="mt-1 font-semibold">{navigation.instruction}</p></div></div>{onCall && <Button type="button" variant="secondary" size="lg" fullWidth icon={<Phone className="h-4 w-4" />} onClick={onCall}>Call</Button>}</div><div className="sticky bottom-0 border-t border-slate-200 bg-white/95 p-4 backdrop-blur-sm sm:p-6"><Button type="button" size="lg" fullWidth onClick={onAction} className="min-h-14 text-base font-semibold">{actionLabel}</Button></div></section>
  </div></div>
);
