export type AdminRole = 'USER' | 'HOSPITAL' | 'AMBULANCE_PROVIDER' | 'AMBULANCE_DRIVER' | 'ADMIN';
export type AdminAccountStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'REJECTED';
export type AdminVerificationStatus = 'PENDING' | 'VERIFIED' | 'REJECTED';

export interface Pagination { page: number; limit: number; total: number; totalPages: number; }
export interface AdminOverview { totalUsers: number; totalHospitals: number; totalAmbulanceProviders: number; totalAmbulances: number; totalAmbulanceDrivers: number; pendingHospitals: number; pendingProviders: number; pendingDrivers: number; activeUsers: number; suspendedUsers: number; verifiedHospitals: number; verifiedProviders: number; verifiedDrivers: number; availableAmbulances:number; busyAmbulances:number; offlineAmbulances:number; maintenanceAmbulances:number; onlineDrivers:number; busyDrivers:number; offlineDrivers:number; activeEmergencies:number; resolvedEmergencies:number; cancelledEmergencies:number; }
export interface AdminUser { id: string; name: string; email: string; phone: string; role: AdminRole; accountStatus: AdminAccountStatus; emailVerified: boolean; phoneVerified: boolean; address?: string; city?: string; state?: string; country?: string; latitude?: number; longitude?: number; createdAt: string; updatedAt: string; }
export interface AdminHospital { id: string; name: string; registrationNumber: string; email: string; phone: string; address?: string; city?: string; state?: string; country?: string; latitude?: number; longitude?: number; hospitalType: string; services: string[]; capabilities: string[]; resourceSummary: Record<string, number>; emergencyAvailability: string; verificationStatus: AdminVerificationStatus; accountStatus: AdminAccountStatus; createdAt: string; updatedAt: string; }
export interface AdminRelationshipRef { id: string; name?: string; registrationNumber?: string; vehicleNumber?: string; }
export interface AdminAmbulanceProvider { id: string; name: string; registrationNumber: string; email: string; phone: string; address?: string; city?: string; state?: string; country?: string; latitude?: number; longitude?: number; serviceType: string; verificationStatus: AdminVerificationStatus; accountStatus: AdminAccountStatus; ambulanceCount: number; createdAt: string; updatedAt: string; }
export interface AdminAmbulance { id: string; registrationNumber: string; vehicleNumber: string; ambulanceType: string; capabilities: string[]; currentStatus: string; currentLatitude?: number; currentLongitude?: number; locationUpdatedAt?: string; locationFreshness:'LIVE'|'RECENT'|'STALE'|'OFFLINE'|'UNKNOWN'; serviceArea?: string; verificationStatus: AdminVerificationStatus; accountStatus: AdminAccountStatus; provider: AdminRelationshipRef | null; assignedDriver: AdminRelationshipRef | null; createdAt: string; updatedAt: string; }
export interface AdminAmbulanceDriver { id: string; fullName: string; email: string; phone: string; licenseNumber: string; licenseVerificationStatus: AdminVerificationStatus; address?: string; city?: string; state?: string; country?: string; registeredLatitude?: number; registeredLongitude?: number; provider: AdminRelationshipRef | null; assignedAmbulance: AdminRelationshipRef | null; availabilityStatus: string; accountStatus: AdminAccountStatus; createdAt: string; updatedAt: string; }
export interface AdminList<T> { items: T[]; pagination: Pagination; }
export interface AdminListParams { page?: number; limit?: number; search?: string; city?: string; role?: AdminRole; status?: AdminAccountStatus; accountStatus?: AdminAccountStatus; verification?: AdminVerificationStatus; provider?: string; currentStatus?: string; availability?: string; hospitalType?: string; from?: string; to?: string; sortBy?: string; sortOrder?: 'asc' | 'desc'; }
