import type { AccountStatus, Role, VerificationStatus } from './roles.js';
export interface Pagination { page:number; limit:number; total:number; totalPages:number; }
export interface AdminOverview {
  totalUsers:number; totalHospitals:number; totalAmbulanceProviders:number; totalAmbulances:number; totalAmbulanceDrivers:number;
  pendingHospitals:number; pendingProviders:number; pendingDrivers:number; activeUsers:number; suspendedUsers:number;
  verifiedHospitals:number; verifiedProviders:number; verifiedDrivers:number;
  availableAmbulances:number; busyAmbulances:number; offlineAmbulances:number; maintenanceAmbulances:number;
  onlineDrivers:number; busyDrivers:number; offlineDrivers:number;
  activeEmergencies:number; resolvedEmergencies:number; cancelledEmergencies:number;
}
export interface AdminUser { id:string; name:string; email:string; phone:string; role:Role; accountStatus:AccountStatus; emailVerified:boolean; phoneVerified:boolean; address?:string; city?:string; state?:string; country?:string; latitude?:number; longitude?:number; createdAt:Date|string; updatedAt:Date|string; }
export interface AdminHospital { id:string; name:string; registrationNumber:string; email:string; phone:string; address?:string; city?:string; state?:string; country?:string; latitude?:number; longitude?:number; hospitalType:string; services:string[]; capabilities:string[]; resourceSummary:Record<string,number>; emergencyAvailability:string; verificationStatus:VerificationStatus; accountStatus:AccountStatus; createdAt:Date|string; updatedAt:Date|string; }
export interface AdminAmbulanceProvider { id:string; name:string; registrationNumber:string; email:string; phone:string; address?:string; city?:string; state?:string; country?:string; latitude?:number; longitude?:number; serviceType:string; verificationStatus:VerificationStatus; accountStatus:AccountStatus; ambulanceCount:number; createdAt:Date|string; updatedAt:Date|string; }
export interface AdminRelationshipRef { id:string; name?:string; registrationNumber?:string; vehicleNumber?:string; }
export interface AdminAmbulance { id:string; registrationNumber:string; vehicleNumber:string; ambulanceType:string; capabilities:string[]; currentStatus:string; currentLatitude?:number; currentLongitude?:number; locationUpdatedAt?:Date|string; locationFreshness:'LIVE'|'RECENT'|'STALE'|'OFFLINE'|'UNKNOWN'; serviceArea?:string; verificationStatus:VerificationStatus; accountStatus:AccountStatus; provider:AdminRelationshipRef|null; assignedDriver:AdminRelationshipRef|null; createdAt:Date|string; updatedAt:Date|string; }
export interface AdminAmbulanceDriver { id:string; fullName:string; email:string; phone:string; licenseNumber:string; licenseVerificationStatus:VerificationStatus; address?:string; city?:string; state?:string; country?:string; registeredLatitude?:number; registeredLongitude?:number; provider:AdminRelationshipRef|null; assignedAmbulance:AdminRelationshipRef|null; availabilityStatus:string; accountStatus:AccountStatus; createdAt:Date|string; updatedAt:Date|string; }