import type { ReactNode } from 'react';
import { useState } from 'react';
import { CheckCircle2, Download } from 'lucide-react';
import { AdminLayout } from '../components/admin/AdminLayout';
import { AdminPage, MetricGrid, Panel } from '../components/admin/AdminPrimitives';
import { CategoryChart, TrendChart } from '../components/admin/AdminCharts';
import { AmbulanceTable, EmergencyTable, HospitalTable, ReportTable, UserTable } from '../components/admin/AdminTables';
import { MapOperationsView } from '../components/admin/MapOperationsView';
import { ADMIN_AMBULANCES, ADMIN_EMERGENCIES, ADMIN_HOSPITALS, ADMIN_METRICS, ADMIN_REPORTS, ADMIN_USERS, DEMAND_AREAS, EMERGENCY_CATEGORIES, REQUEST_TREND, RESPONSE_TREND } from '../data/adminMock';
import { Button } from '../components/common/Button';

const Section = ({ children }: { children: ReactNode }) => <AdminLayout>{children}</AdminLayout>;

export const AdminOverviewPage = () => <Section><AdminPage title="Operations overview" description="Monitor emergency coordination, network readiness and fleet activity. Prototype data only."><MetricGrid metrics={ADMIN_METRICS} /><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><Panel title="Active emergencies" description="Current coordination activity"><EmergencyTable data={ADMIN_EMERGENCIES} /></Panel><Panel title="Network readiness" description="Hospital and ambulance availability"><div className="divide-y divide-slate-100">{ADMIN_HOSPITALS.slice(0, 4).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-semibold">{item.name}</p><p className="mt-0.5 text-xs text-slate-500">{item.area} · {item.availability}</p></div><span className={`text-xs font-semibold ${item.verification === 'Verified' && item.emergencyStatus === 'Operational' ? 'text-emerald-700' : 'text-amber-700'}`}>{item.emergencyStatus}</span></div>)}</div></Panel></div><div className="mt-6"><Panel title="Operational map" description="Demand areas and network activity"><MapOperationsView /></Panel></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><TrendChart title="Emergency requests over time" description="Daily request volume in the prototype period" data={REQUEST_TREND} /><CategoryChart data={EMERGENCY_CATEGORIES} /></div></AdminPage></Section>;
export const AdminEmergenciesPage = () => <Section><AdminPage title="Emergency monitor" description="Decision-oriented view of active and recent emergency coordination."><div className="mb-4 flex items-center gap-2 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-rose-500" />7 active emergencies · prototype data</div><Panel title="Emergency requests"><EmergencyTable data={ADMIN_EMERGENCIES} /></Panel></AdminPage></Section>;
export const AdminHospitalsPage = () => <Section><AdminPage title="Hospital network" description="Review facility verification, emergency readiness and reported availability."><Panel title="Hospitals"><HospitalTable data={ADMIN_HOSPITALS} /></Panel></AdminPage></Section>;
export const AdminAmbulancesPage = () => <Section><AdminPage title="Ambulance network" description="Monitor fleet presence, assignment and operational status."><Panel title="Ambulances"><AmbulanceTable data={ADMIN_AMBULANCES} /></Panel></AdminPage></Section>;
export const AdminUsersPage = () => <Section><AdminPage title="User oversight" description="Anonymized account activity for operational review. No sensitive personal data is shown."><Panel title="Users"><UserTable data={ADMIN_USERS} /></Panel></AdminPage></Section>;
export const AdminReportsPage = () => <Section><AdminPage title="Reports" description="Review facility, emergency and ambulance issues reported to ResQ operations."><Panel title="Reported problems"><ReportTable data={ADMIN_REPORTS} /></Panel></AdminPage></Section>;
export const AdminAnalyticsPage = () => <Section><AdminPage title="Analytics" description="Longer-horizon trends for emergency demand, response performance and network capacity."><div className="grid gap-6 lg:grid-cols-2"><TrendChart title="Emergency trends" description="Request volume by day" data={REQUEST_TREND} /><TrendChart title="Response performance" description="Average response time in minutes" data={RESPONSE_TREND} suffix=" min" /><CategoryChart data={EMERGENCY_CATEGORIES} /><Panel title="Hospital network" description="Readiness snapshot"><div className="space-y-4 p-5">{ADMIN_HOSPITALS.map((hospital) => <div key={hospital.id}><div className="flex justify-between gap-4 text-xs"><span className="font-medium text-slate-700">{hospital.name}</span><span className="text-slate-500">{hospital.availability}</span></div><div className="mt-1 h-2 bg-slate-100"><div className={`h-full ${hospital.emergencyStatus === 'Operational' ? 'w-4/5 bg-slate-700' : hospital.emergencyStatus === 'Limited' ? 'w-2/5 bg-amber-500' : 'w-1/12 bg-rose-600'}`} /></div></div>)}</div></Panel></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Ambulance network" description="Fleet activity snapshot"><div className="grid grid-cols-2 gap-px bg-slate-200"><div className="bg-white p-5"><p className="text-xs text-slate-500">Online</p><p className="mt-1 text-2xl font-bold">{ADMIN_AMBULANCES.filter((x) => x.online).length}</p></div><div className="bg-white p-5"><p className="text-xs text-slate-500">On active assignment</p><p className="mt-1 text-2xl font-bold">{ADMIN_AMBULANCES.filter((x) => ['En Route', 'At Patient', 'At Hospital'].includes(x.status)).length}</p></div></div></Panel><Panel title="Geographic demand" description="Areas with the highest prototype request volume"><div className="divide-y divide-slate-100">{DEMAND_AREAS.map((area) => <div key={area.label} className="flex items-center justify-between px-5 py-3.5"><div><p className="text-sm font-medium">{area.label}</p><p className="text-[11px] text-slate-400">Demand level: {area.level}</p></div><span className="text-sm font-bold">{area.requests}</span></div>)}</div></Panel></div></AdminPage></Section>;
export const AdminSettingsPage = () => { const [saved, setSaved] = useState(false); return <Section><AdminPage title="Settings" description="Prototype-only operations preferences. No backend or authentication is connected."><div className="max-w-2xl space-y-4"><Panel title="Operations preferences"><div className="divide-y divide-slate-100">{['Show prototype data labels', 'Enable operations alerts', 'Require verification before facility activation'].map((label, index) => <label key={label} className="flex cursor-pointer items-center justify-between gap-4 px-5 py-4"><span className="text-sm font-medium">{label}</span><input type="checkbox" defaultChecked={index !== 1} className="h-4 w-4 accent-slate-900" /></label>)}</div></Panel><Button type="button" onClick={() => setSaved(true)}>{saved ? 'Saved' : 'Save preferences'}</Button>{saved && <p className="flex items-center gap-2 text-sm font-medium text-emerald-700"><CheckCircle2 className="h-4 w-4" />Preferences saved locally for this demo session.</p>}<div className="border border-slate-200 bg-white p-5 text-sm text-slate-500"><p className="font-semibold text-slate-900">Prototype environment</p><p className="mt-1">All metrics, statuses and records are mock data. No real emergency or personal information is connected.</p><Button type="button" size="sm" variant="secondary" className="mt-4" icon={<Download className="h-4 w-4" />}>Export prototype data</Button></div></div></AdminPage></Section>; };

export default AdminOverviewPage;
