import type { ReactNode } from 'react';
import { useState } from 'react';
import { ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react';
import { AdminLayout } from '../components/admin/AdminLayout';
import { AdminPage, MetricGrid, Panel } from '../components/admin/AdminPrimitives';
import { CategoryChart, TrendChart } from '../components/admin/AdminCharts';
import { EmergencyTable, ReportTable } from '../components/admin/AdminTables';
import { ADMIN_EMERGENCIES, ADMIN_REPORTS, EMERGENCY_CATEGORIES, REQUEST_TREND, RESPONSE_TREND } from '../data/adminMock';
import { Button } from '../components/common/Button';
import { useAdminAmbulances, useAdminDrivers, useAdminHospitals, useAdminOverview, useAdminProviders, useAdminUsers, useUpdateDriverStatus, useUpdateDriverVerification, useUpdateHospitalStatus, useUpdateHospitalVerification, useUpdateProviderStatus, useUpdateProviderVerification, useUpdateUserStatus } from '../hooks/useAdminManagement';
import type { AdminAccountStatus, AdminAmbulance, AdminAmbulanceDriver, AdminAmbulanceProvider, AdminHospital, AdminUser, AdminVerificationStatus } from '../types/adminManagement';

const Section = ({ children }: { children: ReactNode }) => <AdminLayout>{children}</AdminLayout>;
const ErrorBox = ({ message, retry }: { message: string; retry: () => void }) => <div className="flex items-center justify-between gap-4 border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><span>{message}</span><Button size="sm" variant="secondary" onClick={retry} icon={<RefreshCw className="h-4 w-4" />}>Retry</Button></div>;
const Loading = () => <div className="flex items-center justify-center p-12 text-sm text-slate-500">Loading live admin data…</div>;
const Empty = ({ label }: { label: string }) => <div className="p-10 text-center text-sm text-slate-500">{label}</div>;
const Status = ({ value }: { value: string }) => <span className="inline-flex rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-700">{value}</span>;
const Pager = ({ page, totalPages, onPage }: { page: number; totalPages: number; onPage: (page: number) => void }) => <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>Page {page} of {Math.max(totalPages, 1)}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)} icon={<ChevronLeft className="h-4 w-4" />}>Previous</Button><Button size="sm" variant="secondary" disabled={page >= totalPages} onClick={() => onPage(page + 1)} icon={<ChevronRight className="h-4 w-4" />}>Next</Button></div></div>;
const Search = ({ value, onChange, placeholder = 'Search…' }: { value: string; onChange: (v: string) => void; placeholder?: string }) => <input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm outline-none focus:border-slate-400 focus:ring-2 focus:ring-slate-100" />;
const Select = ({ value, onChange, children }: { value: string; onChange: (v: string) => void; children: ReactNode }) => <select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm outline-none">{children}</select>;
const ConfirmAction = ({ label, onConfirm, disabled = false }: { label: string; onConfirm: () => void; disabled?: boolean }) => <Button size="sm" variant="secondary" disabled={disabled} onClick={() => { if (window.confirm(`Confirm: ${label}?`)) onConfirm(); }}>{label}</Button>;
const message = (error: unknown): string => error instanceof Error ? error.message : 'The operation failed.';

export const AdminOverviewPage = () => {
  const q = useAdminOverview();
  if (q.isLoading) return <Section><AdminPage title="Operations overview" description="Live ResQ platform metrics."><Loading /></AdminPage></Section>;
  if (q.isError || !q.data) return <Section><AdminPage title="Operations overview"><ErrorBox message={message(q.error)} retry={() => void q.refetch()} /></AdminPage></Section>;
  const d = q.data;
  const metrics = [
    { label: 'Users', value: String(d.totalUsers), detail: `${d.activeUsers} active` },
    { label: 'Hospitals', value: String(d.totalHospitals), detail: `${d.verifiedHospitals} verified` },
    { label: 'Providers', value: String(d.totalAmbulanceProviders), detail: `${d.verifiedProviders} verified` },
    { label: 'Ambulances', value: String(d.totalAmbulances), detail: 'Registered fleet' },
    { label: 'Drivers', value: String(d.totalAmbulanceDrivers), detail: `${d.verifiedDrivers} verified` },
    { label: 'Pending', value: String(d.pendingHospitals + d.pendingProviders + d.pendingDrivers), detail: 'Registrations awaiting review' },
  ];
  return <Section><AdminPage title="Operations overview" description="Live MongoDB-backed platform metrics."><MetricGrid metrics={metrics} /><div className="mt-6 grid gap-6 lg:grid-cols-3"><Panel title="Pending registrations"><div className="space-y-3 p-5 text-sm"><div className="flex justify-between"><span>Hospitals</span><b>{d.pendingHospitals}</b></div><div className="flex justify-between"><span>Providers</span><b>{d.pendingProviders}</b></div><div className="flex justify-between"><span>Drivers</span><b>{d.pendingDrivers}</b></div></div></Panel><Panel title="Account health"><div className="space-y-3 p-5 text-sm"><div className="flex justify-between"><span>Active users</span><b>{d.activeUsers}</b></div><div className="flex justify-between"><span>Suspended users</span><b>{d.suspendedUsers}</b></div></div></Panel><Panel title="Verification"><div className="space-y-3 p-5 text-sm"><div className="flex justify-between"><span>Hospitals</span><b>{d.verifiedHospitals}</b></div><div className="flex justify-between"><span>Providers</span><b>{d.verifiedProviders}</b></div><div className="flex justify-between"><span>Drivers</span><b>{d.verifiedDrivers}</b></div></div></Panel></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><TrendChart title="Emergency trends" description="Existing operational analytics" data={REQUEST_TREND} /><CategoryChart data={EMERGENCY_CATEGORIES} /></div></AdminPage></Section>;
};

export const AdminUsersPage = () => {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [role, setRole] = useState(''); const [page, setPage] = useState(1); const q = useAdminUsers({ page, limit: 20, search, status: status as AdminAccountStatus | undefined, role: role as AdminUser['role'] | undefined }); const mutation = useUpdateUserStatus();
  return <Section><AdminPage title="User oversight" description="Search, inspect and manage registered accounts."><Panel title="Users"><div className="grid gap-2 border-b border-slate-200 p-4 md:grid-cols-[1fr_auto_auto]"><Search value={search} onChange={(v) => { setSearch(v); setPage(1); }} placeholder="Name, email or phone" /><Select value={role} onChange={(v) => { setRole(v); setPage(1); }}><option value="">All roles</option><option>USER</option><option>HOSPITAL</option><option>AMBULANCE_PROVIDER</option><option>AMBULANCE_DRIVER</option><option>ADMIN</option></Select><Select value={status} onChange={(v) => { setStatus(v); setPage(1); }}><option value="">All statuses</option><option>ACTIVE</option><option>PENDING</option><option>SUSPENDED</option><option>REJECTED</option></Select></div>{q.isLoading ? <Loading /> : q.isError ? <ErrorBox message={message(q.error)} retry={() => void q.refetch()} /> : !q.data?.items.length ? <Empty label="No users match these filters." /> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-4 py-3">User</th><th>Role</th><th>Status</th><th>Location</th><th>Verification</th><th>Action</th></tr></thead><tbody>{q.data.items.map((u) => <tr key={u.id} className="border-b border-slate-100"><td className="px-4 py-3"><b>{u.name}</b><div className="text-xs text-slate-500">{u.email} · {u.phone}</div></td><td><Status value={u.role} /></td><td><Status value={u.accountStatus} /></td><td>{u.city ?? '—'}, {u.state ?? '—'}</td><td>{u.emailVerified && u.phoneVerified ? 'Verified' : 'Partial'}</td><td><ConfirmAction label={u.accountStatus === 'SUSPENDED' ? 'Activate' : 'Suspend'} disabled={mutation.isPending} onConfirm={() => mutation.mutate({ id: u.id, status: u.accountStatus === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' })} /></td></tr>)}</tbody></table></div><Pager {...q.data.pagination} onPage={setPage} /></>}</Panel></AdminPage></Section>;
};

function ApprovalActions({ id, verification, accountStatus, verify, changeStatus }: { id: string; verification: AdminVerificationStatus; accountStatus: AdminAccountStatus; verify: (id: string, status: AdminVerificationStatus) => void; changeStatus: (id: string, status: Extract<AdminAccountStatus, 'ACTIVE' | 'SUSPENDED' | 'REJECTED'>) => void }) { return <div className="flex flex-wrap gap-2"><Status value={`V: ${verification}`} /><Status value={`A: ${accountStatus}`} />{verification !== 'VERIFIED' && <ConfirmAction label="Verify" onConfirm={() => verify(id, 'VERIFIED')} />}{verification !== 'REJECTED' && <ConfirmAction label="Reject" onConfirm={() => verify(id, 'REJECTED')} />}{accountStatus === 'SUSPENDED' ? <ConfirmAction label="Activate" onConfirm={() => changeStatus(id, 'ACTIVE')} /> : <ConfirmAction label="Suspend" onConfirm={() => changeStatus(id, 'SUSPENDED')} />}</div>; }

export const AdminHospitalsPage = () => {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const q = useAdminHospitals({ page, limit: 20, search }); const verification = useUpdateHospitalVerification(); const status = useUpdateHospitalStatus();
  return <Section><AdminPage title="Hospital network" description="Real registrations with separate verification and account status."><Panel title="Hospitals"><div className="p-4"><Search value={search} onChange={(v) => { setSearch(v); setPage(1); }} placeholder="Hospital, registration number, email or phone" /></div>{q.isLoading ? <Loading /> : q.isError ? <ErrorBox message={message(q.error)} retry={() => void q.refetch()} /> : !q.data?.items.length ? <Empty label="No hospitals found." /> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-4 py-3">Hospital</th><th>Type</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{q.data.items.map((h: AdminHospital) => <tr key={h.id} className="border-b border-slate-100 align-top"><td className="px-4 py-3"><b>{h.name}</b><div className="text-xs text-slate-500">{h.registrationNumber} · {h.email}</div></td><td>{h.hospitalType}</td><td>{h.city ?? '—'}, {h.state ?? '—'}</td><td><Status value={h.verificationStatus} /><div className="mt-1"><Status value={h.accountStatus} /></div></td><td><ApprovalActions id={h.id} verification={h.verificationStatus} accountStatus={h.accountStatus} verify={(id,v) => verification.mutate({ id, verificationStatus: v })} changeStatus={(id,s) => status.mutate({ id, status: s })} /></td></tr>)}</tbody></table></div><Pager {...q.data.pagination} onPage={setPage} /></>}</Panel></AdminPage></Section>;
};

export const AdminAmbulancesPage = () => {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const q = useAdminAmbulances({ page, limit: 20, search });
  return <Section><AdminPage title="Ambulance network" description="Live fleet registrations, relationships and current location data."><Panel title="Ambulances"><div className="p-4"><Search value={search} onChange={(v) => { setSearch(v); setPage(1); }} placeholder="Registration, vehicle number or type" /></div>{q.isLoading ? <Loading /> : q.isError ? <ErrorBox message={message(q.error)} retry={() => void q.refetch()} /> : !q.data?.items.length ? <Empty label="No ambulances found." /> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-4 py-3">Ambulance</th><th>Provider</th><th>Driver</th><th>Status</th><th>Location</th></tr></thead><tbody>{q.data.items.map((a: AdminAmbulance) => <tr key={a.id} className="border-b border-slate-100"><td className="px-4 py-3"><b>{a.registrationNumber}</b><div className="text-xs text-slate-500">{a.vehicleNumber} · {a.ambulanceType}</div></td><td>{a.provider?.name ?? 'Unassigned'}</td><td>{a.assignedDriver?.name ?? 'Unassigned'}</td><td><Status value={a.currentStatus} /><div className="mt-1"><Status value={a.verificationStatus} /></div></td><td>{a.currentLatitude !== undefined && a.currentLongitude !== undefined ? `${a.currentLatitude}, ${a.currentLongitude}` : 'No current location'}</td></tr>)}</tbody></table></div><Pager {...q.data.pagination} onPage={setPage} /></>}</Panel></AdminPage></Section>;
};

export const AdminProvidersPage = () => { const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const q=useAdminProviders({page,limit:20,search}); const v=useUpdateProviderVerification(); const s=useUpdateProviderStatus(); return <Section><AdminPage title="Ambulance providers" description="Manage provider verification, account status and fleet relationships."><Panel title="Providers"><div className="p-4"><Search value={search} onChange={(x)=>{setSearch(x);setPage(1)}} placeholder="Provider, registration, email or phone"/></div>{q.isLoading?<Loading/>:q.isError?<ErrorBox message={message(q.error)} retry={()=>void q.refetch()}/>:!q.data?.items.length?<Empty label="No providers found."/>:<><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-4 py-3">Provider</th><th>Location</th><th>Fleet</th><th>Status</th><th>Actions</th></tr></thead><tbody>{q.data.items.map((p:AdminAmbulanceProvider)=><tr key={p.id} className="border-b border-slate-100 align-top"><td className="px-4 py-3"><b>{p.name}</b><div className="text-xs text-slate-500">{p.registrationNumber} · {p.email}</div></td><td>{p.city??'—'}, {p.state??'—'}</td><td>{p.ambulanceCount}</td><td><Status value={p.verificationStatus}/><div className="mt-1"><Status value={p.accountStatus}/></div></td><td><ApprovalActions id={p.id} verification={p.verificationStatus} accountStatus={p.accountStatus} verify={(id,x)=>v.mutate({id,verificationStatus:x})} changeStatus={(id,x)=>s.mutate({id,status:x})}/></td></tr>)}</tbody></table></div><Pager {...q.data.pagination} onPage={setPage}/></>}</Panel></AdminPage></Section>; };

export const AdminDriversPage = () => { const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const q=useAdminDrivers({page,limit:20,search}); const v=useUpdateDriverVerification(); const s=useUpdateDriverStatus(); return <Section><AdminPage title="Ambulance drivers" description="Review driver verification, registered location and fleet assignment."><Panel title="Drivers"><div className="p-4"><Search value={search} onChange={(x)=>{setSearch(x);setPage(1)}} placeholder="Name, email, phone or license"/></div>{q.isLoading?<Loading/>:q.isError?<ErrorBox message={message(q.error)} retry={()=>void q.refetch()}/>:!q.data?.items.length?<Empty label="No drivers found."/>:<><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-4 py-3">Driver</th><th>Provider</th><th>Ambulance</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{q.data.items.map((d:AdminAmbulanceDriver)=><tr key={d.id} className="border-b border-slate-100 align-top"><td className="px-4 py-3"><b>{d.fullName}</b><div className="text-xs text-slate-500">{d.email} · {d.licenseNumber}</div></td><td>{d.provider?.name??'Unassigned'}</td><td>{d.assignedAmbulance?.registrationNumber??'Unassigned'}</td><td>{d.city??'—'}, {d.state??'—'}</td><td><Status value={d.licenseVerificationStatus}/><div className="mt-1"><Status value={d.accountStatus}/></div></td><td><ApprovalActions id={d.id} verification={d.licenseVerificationStatus} accountStatus={d.accountStatus} verify={(id,x)=>v.mutate({id,verificationStatus:x})} changeStatus={(id,x)=>s.mutate({id,status:x})}/></td></tr>)}</tbody></table></div><Pager {...q.data.pagination} onPage={setPage}/></>}</Panel></AdminPage></Section>; };

export const AdminEmergenciesPage = () => <Section><AdminPage title="Emergency monitor" description="Existing emergency coordination UI remains available."><Panel title="Emergency requests"><EmergencyTable data={ADMIN_EMERGENCIES} /></Panel></AdminPage></Section>;
export const AdminReportsPage = () => <Section><AdminPage title="Reports" description="Existing reports UI remains available."><Panel title="Reported problems"><ReportTable data={ADMIN_REPORTS} /></Panel></AdminPage></Section>;
export const AdminAnalyticsPage = () => <Section><AdminPage title="Analytics" description="Existing analytics remain available while operational APIs are introduced separately."><div className="grid gap-6 lg:grid-cols-2"><TrendChart title="Emergency trends" description="Existing request volume" data={REQUEST_TREND} /><TrendChart title="Response performance" description="Existing response trend" data={RESPONSE_TREND} suffix=" min" /><CategoryChart data={EMERGENCY_CATEGORIES} /></div></AdminPage></Section>;
export const AdminSettingsPage = () => <Section><AdminPage title="Settings" description="Operational settings are not part of this management API scope."><Panel title="Status"><div className="p-5 text-sm text-slate-600">Admin authentication and authorization remain enforced by the backend. No settings are persisted by this feature.</div></Panel></AdminPage></Section>;
export default AdminOverviewPage;
