import { useState } from 'react';
import { Ambulance, BedDouble, Building2, Check, CircleAlert, MapPin, ShieldCheck, UserRound, X } from 'lucide-react';
import { Button } from '../components/common/Button';
import { StatusBadge } from '../components/common/StatusBadge';
import { MapView } from '../components/map/MapView';
import { MOCK_AMBULANCES, MOCK_EMERGENCIES, MOCK_HOSPITAL, MOCK_PATIENTS, MOCK_RESOURCES } from '../data/hospitalMock';
import type { EmergencyRequest, HospitalOperationalStatus, HospitalResource } from '../types/hospital';

const wrap='mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8'; const box='border border-slate-200 bg-white';
export const HospitalPage=()=>{
 const path=window.location.pathname; const [requests,setRequests]=useState<EmergencyRequest[]>(MOCK_EMERGENCIES); const [resources,setResources]=useState<HospitalResource[]>(MOCK_RESOURCES); const [selectedId,setSelectedId]=useState(MOCK_EMERGENCIES[0].id); const selected=requests.find(x=>x.id===selectedId)??requests[0];
 const setRequest=(status:EmergencyRequest['status'])=>setRequests(xs=>xs.map(x=>x.id===selected.id?{...x,status}:x)); const setResource=(id:string,status:HospitalOperationalStatus)=>setResources(xs=>xs.map(x=>x.id===id?{...x,status}:x));
 if(path==='/hospital/emergencies')return <div className={wrap}><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className={box}><header className="border-b border-slate-200 p-4"><h2 className="text-lg font-semibold">Emergency Requests</h2><p className="mt-1 text-xs text-slate-500">Prototype data. No real notification is sent.</p></header>{requests.map(r=><button key={r.id} type="button" onClick={()=>setSelectedId(r.id)} className={`w-full border-b border-slate-100 p-4 text-left hover:bg-slate-50 ${selected.id===r.id?'bg-slate-50':''}`}><div className="flex justify-between gap-3"><div><p className="font-semibold">{r.id} · {r.category}</p><p className="mt-1 text-sm text-slate-500">{r.approximateLocation}</p></div><StatusBadge variant={r.status==='Accepted'?'verified':'waitTime'} label={r.status}/></div><div className="mt-3 grid grid-cols-2 gap-3 text-xs text-slate-600 sm:grid-cols-4"><span>ETA<b className="block text-slate-900">{r.eta}</b></span><span>Capability<b className="block text-slate-900">{r.requiredCapability}</b></span><span>Ambulance<b className="block text-slate-900">{r.ambulanceStatus}</b></span><span>State<b className="block text-slate-900">{r.status==='Accepted'?'Preparing':r.status}</b></span></div></button>)}</section><section className={`${box} h-fit p-5`}><p className="text-xs uppercase tracking-wider text-slate-500">Selected request</p><h2 className="mt-1 text-xl font-semibold">{selected.id}</h2><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-slate-500">Emergency</dt><dd className="font-medium">{selected.category}</dd></div><div><dt className="text-slate-500">Location</dt><dd className="font-medium">{selected.approximateLocation}</dd></div><div><dt className="text-slate-500">ETA</dt><dd className="font-medium">{selected.eta}</dd></div><div><dt className="text-slate-500">Capability</dt><dd className="font-medium">{selected.requiredCapability}</dd></div><div><dt className="text-slate-500">Ambulance</dt><dd className="font-medium">{selected.ambulanceStatus}</dd></div></dl><div className="mt-6 grid grid-cols-2 gap-2"><Button disabled={selected.status!=='Pending'} onClick={()=>setRequest('Accepted')} icon={<Check className="h-4 w-4"/>}>Accept Request</Button><Button disabled={selected.status!=='Pending'} variant="secondary" onClick={()=>setRequest('Declined')} icon={<X className="h-4 w-4"/>}>Decline</Button></div>{selected.status==='Accepted'&&<p className="mt-3 text-xs font-medium text-emerald-700">Preparing for incoming patient.</p>}</section></div></div>;
 if(path==='/hospital/patients')return <div className={wrap}><section className={box}><header className="border-b border-slate-200 p-4"><h2 className="text-lg font-semibold">Incoming Patients</h2><p className="mt-1 text-sm text-slate-500">Operational cases only. Personal information omitted.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Case ID</th><th>Emergency Type</th><th>ETA</th><th>Ambulance</th><th>Status</th></tr></thead><tbody className="divide-y divide-slate-100">{MOCK_PATIENTS.map(p=><tr key={p.id}><td className="px-4 py-4 font-semibold">{p.id}</td><td>{p.emergencyType}</td><td>{p.eta}</td><td>{p.ambulance}</td><td><StatusBadge variant="neutral" label={p.status}/></td></tr>)}</tbody></table></div></section></div>;
 if(path==='/hospital/ambulances')return <div className={wrap}><section className={box}><header className="border-b border-slate-200 p-4"><h2 className="text-lg font-semibold">Ambulances</h2><p className="mt-1 text-sm text-slate-500">Prepared for future live tracking.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Ambulance ID</th><th>Status</th><th>ETA</th><th>Current Trip</th><th>Destination</th></tr></thead><tbody className="divide-y divide-slate-100">{MOCK_AMBULANCES.map(a=><tr key={a.id}><td className="px-4 py-4 font-semibold">{a.id}</td><td><StatusBadge variant={a.status==='Available'?'verified':'neutral'} label={a.status}/></td><td>{a.eta}</td><td>{a.currentTrip}</td><td>{a.destination}</td></tr>)}</tbody></table></div></section></div>;
 if(path==='/hospital/resources')return <div className={wrap}><section className={`${box} max-w-3xl`}><header className="border-b border-slate-200 p-4"><h2 className="text-lg font-semibold">Hospital Resources</h2><p className="mt-1 text-sm text-slate-500">Mock status editing only.</p></header>{resources.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-slate-100 p-4"><div><p className="font-medium">{r.name}</p><p className="text-xs text-slate-500">{r.available} of {r.total} available</p></div><span className="rounded-md border border-slate-200 px-2 py-1 text-xs">{r.status}</span><select value={r.status} onChange={e=>setResource(r.id,e.target.value as HospitalOperationalStatus)} className="rounded-md border border-slate-200 px-2 py-2 text-xs"><option>Available</option><option>Limited</option><option>Unavailable</option></select></div>)}</section></div>;
 if(path==='/hospital/profile')return <div className={wrap}><section className={`${box} max-w-2xl p-5`}><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-100"><Building2 className="h-6 w-6"/></div><div><h2 className="text-xl font-semibold">{MOCK_HOSPITAL.name}</h2><div className="mt-2"><StatusBadge variant="verified" label={MOCK_HOSPITAL.verification}/></div></div></div><dl className="mt-7 divide-y divide-slate-100 text-sm">{[['Address',MOCK_HOSPITAL.address],['Phone',MOCK_HOSPITAL.phone],['Emergency contact',MOCK_HOSPITAL.emergencyContact],['Emergency department',MOCK_HOSPITAL.emergencyDepartment]].map(([a,b])=><div key={a} className="grid gap-1 py-3 sm:grid-cols-[180px_1fr]"><dt className="text-slate-500">{a}</dt><dd className="font-medium">{b}</dd></div>)}</dl></section></div>;
 const metrics=[['Emergency Requests',String(requests.filter(r=>r.status!=='Declined').length),CircleAlert],['Incoming Patients','4',UserRound],['Incoming Ambulances','3',Ambulance],['ICU Availability','7 available',BedDouble],['Emergency Beds','12 available',Building2],['Trauma Availability','3 available',ShieldCheck]] as const;
 return <div className={wrap}><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">Prototype / demo data</p><h2 className="mt-1 text-2xl font-semibold">{MOCK_HOSPITAL.name}</h2><p className="mt-1 text-sm text-slate-500">{MOCK_HOSPITAL.address}</p></div><StatusBadge variant="verified" label="Verified hospital"/></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label,value,Icon])=><div key={label} className={`${box} p-4`}><div className="flex justify-between"><p className="text-sm text-slate-500">{label}</p><Icon className="h-4 w-4 text-slate-400"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><section className={box}><header className="border-b border-slate-200 p-4"><h3 className="font-semibold">Emergency operations</h3><p className="mt-1 text-xs text-slate-500">Incoming requests requiring coordination.</p></header>{requests.map(r=><div key={r.id} className="border-b border-slate-100 p-4"><div className="flex justify-between"><div><p className="font-semibold">{r.id} · {r.category}</p><p className="mt-1 text-sm text-slate-500">{r.approximateLocation}</p></div><StatusBadge variant={r.status==='Accepted'?'verified':'waitTime'} label={r.status}/></div><div className="mt-3 flex flex-wrap gap-5 text-xs text-slate-600"><span>ETA <b className="text-slate-900">{r.eta}</b></span><span>Ambulance <b className="text-slate-900">{r.ambulanceStatus}</b></span><span>Capability <b className="text-slate-900">{r.requiredCapability}</b></span></div></div>)}</section><section className={`${box} overflow-hidden`}><header className="border-b border-slate-200 p-4"><h3 className="font-semibold">Operations area</h3><p className="mt-1 text-xs text-slate-500">Existing ResQ map abstraction.</p></header><div className="h-80"><MapView interactive className="h-full" center={{latitude:26.9124,longitude:75.7873}} userLocation={{latitude:26.9124,longitude:75.7873,accuracy:'high',label:'Hospital area'}}/></div><p className="border-t border-slate-200 p-3 text-xs text-slate-500"><MapPin className="mr-1 inline h-3.5 w-3.5"/>Map is a prototype placeholder.</p></section></div></div>;
};
